name: Refetch data

permissions:
    contents: write

on:
        workflow_dispatch:
        push:
                paths:
                        - 'get_data.js'
                        - 'package.json'
                        - 'package-lock.json'
        schedule:
                - cron: '0 0 * * 0' # weekly: Sundays at 00:00 UTC

jobs:
        refetch:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout repository
                          uses: actions/checkout@v4
                          with:
                                persist-credentials: true
                                fetch-depth: 0

                        - name: Setup Node.js
                          uses: actions/setup-node@v4
                          with:
                            node-version: '18'

                        - name: Install dependencies if missing and run get_data
                          run: |
                                        if [ ! -d node_modules ]; then
                                                echo "node_modules not found, running npm i"
                                                npm i
                                        else
                                                echo "node_modules found, skipping npm i"
                                        fi
                                        node get_data.js

                        - name: Commit and push data.json if changed
                          run: |
                                        git config user.name "github-actions[bot]"
                                        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                                        # Only commit if data.json changed
                                        if git diff --quiet --exit-code -- data.json; then
                                            echo "No changes in data.json"
                                        else
                                            git add data.json
                                            git commit -m "Update data.json [skip ci]"
                                            git push
                                        fi